### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by ENikS** [stebet/DependencyInjectorBenchmarks#11]
Are you planning to develop your benchmarks more? It would be nice to have a project comparing containers using proper tools.

**Comment by stebet** [comment]
Yeah. Been busy with a lot of other stuff recently. I'm going to do a NuGet update on this soonish and take it a little further.

**Comment by ENikS** [comment]
There is a collaborative [effort](https://github.com/benchmarks/ioc-containers) with [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) team. We are trying to create impartial platform for all kinds of 'competitions'.  Would you care to join?

**Comment by stebet** [comment]
Of course :)
