### ISSUE TITLE
StructureMap singleton is using Unity

### ISSUE THREAD

**Issue by schotime** [stebet/DependencyInjectorBenchmarks#5]
Hey,
It looks like my fix didn't make it into the pull request. But this needs to be changed to the structuremap one.

https://github.com/stebet/DependencyInjectorBenchmarks/blob/master/src/DependencyInjectorBenchmarks/SingletonBenchmark.cs#L43

Cheers,
Adam

**Comment by Bobris** [comment]
My pull request #4 also contains this fix.

**Comment by stebet** [comment]
Thanks for this. I bit late taking a look, but saw it now that I wanted to update the benchmark. thanks a lot :) This has now been merged.
